nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173/']
        allow_headers: ['Content-Type', 'Authorization', 'origin','accept', 'bearer', 'x-requested-with', 'x-csrf-token', 'x-xsrf-token', 'x-www-form-urlencoded']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/':
            allow_origin: ['http://localhost/5173']
            allow_headers: ['Content-Type', 'Authorization', 'origin','accept', 'bearer', 'x-requested-with', 'x-csrf-token', 'x-xsrf-token', 'x-www-form-urlencoded']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600